#!/bin/sh
# make sure the filename is used as the account name
default_user=':filename'

# pass custom rofi flags
_rofi() {
	rofi \
		-i \
		-no-auto-select \
		-config "$XDG_CONFIG_HOME/rofi-pass/rofi.rasi" \
		"$@"
}

_do_type_xdotool() {
	fcitx5-temp-off # see ~/.local/share/bin

	# tr -d required because the "path" variable ends in a newline character
	tr -d '\n' |\
		xdotool type --delay ${type_delay} --clearmodifiers --file -
	# xdotool command is otherwise not modified

	fcitx5-temp-restore
}

