#!/bin/sh
. "$HOME/.profile"
xrdb -override < "$XDG_CONFIG_HOME/X11/base"
mode --no-reload restore

/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
polybar &
picom &
xbanish &
dunst &
autocutsel -selection CLIPBOARD &
fcitx5 &
xbindkeys --nodaemon &
{% if yadm.hostname == "thoncc" %}
xdimmer -t 45 -p 3 &
{% else %}
redshift -l 52:6 &
nicotine --hidden &
desktop2mqtt --config "$XDG_CONFIG_HOME/desktop2mqtt/config.yml" &
{% endif %}

# auto start lazy script after everything else
[ -x "$HOME/do.sh" ] && "$HOME/do.sh" &

exit_trap() {
	trap - TERM
	kill -- -$$
}
trap exit_trap INT TERM EXIT

# I want to keep this script running so I can easily kill all daemons when i3
# exits
wait $(jobs -p)
