#!/bin/sh
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
cat ~/.config/X11/base ~/.config/X11/dark | xrdb &
polybar main -c ~/.config/polybar/config &
zsh -c "rwall" &
picom -b
xbanish &
redshift &
dunst &
flashfocus &
xset r rate 250 40
autocutsel &
sh ~/.bwunlock &
zsh -c "xbindkeys -f ~/.config/xbindkeys/main"

