#!/bin/sh
. ~/.profile
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
cat "$XDG_CONFIG_HOME/X11/$(cat "$XDG_DATA_HOME/mode/active")" | xrdb -merge &
polybar &
rwall &
picom -b
xbanish &
dunst &
autocutsel &
fcitx5 -d
xbindkeys -f "~/.config/xbindkeys/main"
{% if yadm.hostname == "thoncc" %}
xdimmer -t 45 -p 3 &
light-locker --no-late-locking &
{% else %}
redshift -l 52:6 &
nicotine &
{% endif %}
flashfocus &

# bw unlock <password> --raw | keyctl padd user bw_session @u
sh ~/.config/i3/unlock_bitwarden &

# auto start lazy script after everything else
sleep 2
[ -f "~/do.sh" ] && . "~/do.sh"

