#!/bin/sh
mkcd "$XDG_CONFIG_HOME/dunst"
cat 'base' - << EOF > 'dunstrc'
frame_color = "$accent"

[urgency_low]
background = "$bg"
foreground = "$fg"
timeout = 10

[urgency_normal]
background = "$bg"
foreground = "$fg"
timeout = 10

[urgency_critical]
background = "$color1"
foreground = "$bg"
frame_color = "$color1"
timeout = 0
EOF

