#!/bin/sh
cat "$XDG_DATA_HOME/fcitx5/themes/loek/base.conf" - << EOF > "$XDG_DATA_HOME/fcitx5/themes/loek/theme.conf"
[InputPanel]
NormalColor=$fg
HighlightCandidateColor=$accent_text
HighlightColor=$color13
HighlightBackgroundColor=$bg

[InputPanel/Background]
Color=$bg
BorderColor=$accent

[InputPanel/Highlight]
Color=$accent

[Menu/Background]
Color=$bg

[Menu]
NormalColor=$fg

[Menu/Highlight]
Color=$accent

[Menu/Separator]
Color=$color7
EOF

