#!/bin/sh
[ $no_cfg -eq 1 ] && return

mkcd "$XDG_CONFIG_HOME/polybar"
cat << EOF > 'colors.ini'
[color]
bg = \${xrdb:background:$bg}
fg = \${xrdb:foreground:$fg}
fg-alt = \${xrdb:background:$bg}
fg-half = \${xrdb:color8:$color8}

alpha = #00000000

; vim:ft=dosini
EOF

