#!/bin/sh
[ $no_cfg -eq 1 ] && return

mkcd "$XDG_CONFIG_HOME/zathura"
cat << EOF > 'colors'
set completion-bg "$bg"
set completion-fg "$fg"
set completion-highlight-bg "$accent"
set completion-highlight-fg "$accent_text"
set default-bg "$bg"
set default-fg "$fg"
set highlight-active-color "$(echo "$accent" | pastel set alpha 0.5 | pastel format rgb)"
set highlight-color "$(echo "$accent_text" | pastel set alpha 0.5 | pastel format rgb)"
set inputbar-bg "$bg"
set inputbar-fg "$fg"
set notification-bg "$bg"
set notification-error-bg "$color9"
set notification-error-fg "$bg"
set notification-fg "$fg"
set notification-warning-bg "$color9"
set notification-warning-fg "$bg"
set recolor-darkcolor "$fg"
set recolor-lightcolor "$bg"
set statusbar-bg "$bg"
set statusbar-fg "$fg"
EOF

