#!/bin/sh

# lightline
cat - "$XDG_CONFIG_HOME/nvim/lightline-base.vim" << EOF > "$XDG_CONFIG_HOME/nvim/lightline.vim"
let s:bg = [ '$bg', 'NONE' ]
let s:fg = [ '$fg', 'NONE' ]
let s:mode = [ '$color0', 'NONE' ]
let s:faint = [ '$color8', 'NONE' ]
let s:none = [ 'NONE', 'NONE' ]
let s:test = [ '#ff00ff', 'NONE' ]
EOF

# terminal colors
cat << EOF > "$XDG_CONFIG_HOME/nvim/termcolors.vim"
let g:terminal_color_0 = '$color0'
let g:terminal_color_1 = '$color1'
let g:terminal_color_2 = '$color2'
let g:terminal_color_3 = '$color3'
let g:terminal_color_4 = '$color4'
let g:terminal_color_5 = '$color5'
let g:terminal_color_6 = '$color6'
let g:terminal_color_7 = '$color7'
let g:terminal_color_8 = '$color8'
let g:terminal_color_9 = '$color9'
let g:terminal_color_10 = '$color10'
let g:terminal_color_11 = '$color11'
let g:terminal_color_12 = '$color12'
let g:terminal_color_13 = '$color13'
let g:terminal_color_14 = '$color14'
let g:terminal_color_15 = '$color15'
EOF

