#!/bin/sh
# create accent color differently for dark/light mode

# do not generate accent color if already explicitly defined by theme
[ -n "$accent" ] && return

if [ "$mode" = "light" ] ; then
	themevar accent "$color15"
	themevar accent_text "$color0"
fi
if [ "$mode" = "dark" ] ; then
	themevar accent "$(mix_rgb $bg $color0 0.5)"
	themevar accent_text "$fg"
fi

