--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/loek/.config/wpg/wallpapers/pywal.png"

-- Special
background="#312322"
foreground="#cbc8c7"
cursor="#cbc8c7"

-- Colors
color0="#312322"
color1="#c3acaa"
color2="#8eb8fb"
color3="#f4b3aa"
color4="#c0c3ef"
color5="#e9bce1"
color6="#bed5fb"
color7="#cbc8c7"
color8="#645a59"
color9="#c3acaa"
color10="#8eb8fb"
color11="#f4b3aa"
color12="#c0c3ef"
color13="#e9bce1"
color14="#bed5fb"
color15="#cbc8c7"
