--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/loek/.config/wpg/wallpapers/pywal.png"

-- Special
background="#141415"
foreground="#c4c4c4"
cursor="#c4c4c4"

-- Colors
color0="#141415"
color1="#292b37"
color2="#3c2a27"
color3="#3b3033"
color4="#3f3330"
color5="#4b4240"
color6="#66615a"
color7="#c4c4c4"
color8="#4e4e4f"
color9="#292b37"
color10="#3c2a27"
color11="#3b3033"
color12="#3f3330"
color13="#4b4240"
color14="#66615a"
color15="#c4c4c4"
