# Shell variables
# Generated by 'wal'
wallpaper='/home/loek/.config/wpg/wallpapers/pywal.png'

# Special
background='#151618'
foreground='#c4c4c5'
cursor='#c4c4c5'

# Colors
color0='#151618'
color1='#131e35'
color2='#222323'
color3='#1d2841'
color4='#2a2929'
color5='#2a313f'
color6='#303d57'
color7='#c4c4c5'
color8='#4f5051'
color9='#131e35'
color10='#222323'
color11='#1d2841'
color12='#2a2929'
color13='#2a313f'
color14='#303d57'
color15='#c4c4c5'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
