# Shell variables
# Generated by 'wal'
wallpaper='/home/loek/.config/wpg/wallpapers/pywal.png'

# Special
background='#1e1e1f'
foreground='#c6c6c7'
cursor='#c6c6c7'

# Colors
color0='#1e1e1f'
color1='#666b6d'
color2='#8a8c8d'
color3='#c59683'
color4='#a7aeb0'
color5='#aabbbe'
color6='#d1c494'
color7='#c6c6c7'
color8='#565657'
color9='#666b6d'
color10='#8a8c8d'
color11='#c59683'
color12='#a7aeb0'
color13='#aabbbe'
color14='#d1c494'
color15='#c6c6c7'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
