--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/loek/.config/wpg/wallpapers/pywal.png"

-- Special
background="#1c1c1c"
foreground="#c6c6c6"
cursor="#c6c6c6"

-- Colors
color0="#1c1c1c"
color1="#616c71"
color2="#7f8485"
color3="#9099ba"
color4="#c79c95"
color5="#9fc0c8"
color6="#e4b695"
color7="#c6c6c6"
color8="#545454"
color9="#616c71"
color10="#7f8485"
color11="#9099ba"
color12="#c79c95"
color13="#9fc0c8"
color14="#e4b695"
color15="#c6c6c6"
