# Shell variables
# Generated by 'wal'
wallpaper='/home/loek/.config/wpg/wallpapers/pywal.png'

# Special
background='#312322'
foreground='#cbc8c7'
cursor='#cbc8c7'

# Colors
color0='#312322'
color1='#c3acaa'
color2='#8eb8fb'
color3='#f4b3aa'
color4='#c0c3ef'
color5='#e9bce1'
color6='#bed5fb'
color7='#cbc8c7'
color8='#645a59'
color9='#c3acaa'
color10='#8eb8fb'
color11='#f4b3aa'
color12='#c0c3ef'
color13='#e9bce1'
color14='#bed5fb'
color15='#cbc8c7'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
