#!/bin/sh
# ensure we are running on arch linux
[ ! -e /etc/os-release ] && exit 0
. /etc/os-release
[ "$ID" != 'arch' ] && exit 0

# resolve files in this script relative to this script's location
cd "$(dirname "$0")"

# filter comments and pipe package name list to yay
sed -e 's/#.*//g' -e 's/ //g' -e '/^$/d' packages-arch | yay --needed -Sy -

