#!/bin/sh
# warn if the vim theme is not installed
if [ "$(find "$XDG_CONFIG_HOME/nvim" -name "$vim_theme_name.vim" | wc -l)" -eq 0 ] ; then
	echo "warn: vim theme $vim_theme_name does not appear to be installed" >&2
fi
themevar vim_theme_name
