#!/bin/sh
export mode='light'

export color0='#d1d5da'
export color1='#cb2431'
export color2='#22863a'
export color3='#b08800'
export color4='#005cc5'
export color5='#5a32a3'
export color6='#3192aa'
export color7='#6a737d'
export color8='#959da5'
export color9='#d73a49'
export color10='#28a745'
export color11='#dbab09'
export color12='#0366d6'
export color13='#5a32a3'
export color14='#1b7c83'
export color15='#24292e'

export bg='#ffffff'
export fg='#24292e'

export vim_theme_name='github-light'
